# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\common\Current\ASS_test\Auto_submitting_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from convert import testGenerating
from login import getInfoList
from saveInfo import saveInfoList

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 120, 200, 100))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 40, 200, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 190, 200, 100))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 400, 300))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 420, 200, 100))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.generateNewDocx) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.getInfo) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "生成快报（测试）"))
        self.pushButton_2.setText(_translate("MainWindow", "获取信息（测试）"))
        self.label.setText(_translate("MainWindow", "获取信息预览："))
        self.pushButton_3.setText(_translate("MainWindow", "确认后继续"))

    def generateNewDocx(self):
        testGenerating()
        self.label_2.setText("快报已生成")
    
    def getInfo(self):
        infoList = getInfoList()
        self.label_2.setWordWrap(True)
        self.label_2.setText("攻击源ip：" + infoList[0] + "\n" +
                             "被攻击ip：" + infoList[1] + "\n" +
                             "攻击时间：" + infoList[2] + "\n" +
                             "攻击方式：" + infoList[3])
        saveInfoList(infoList)